import { Listing } from "@/types/listing";

const BUILDING_ILLUSTRATION_COUNT = 6;

// 실제 매물 사진이 없는 샘플 데이터이므로, 무작위 스톡 사진(엉뚱한 풍경 등) 대신
// 사무실/빌딩 테마의 자체 제작 일러스트를 시드값 기준으로 결정적으로 배정한다.
function PLACEHOLDER_IMG(seed: string) {
  const hash = [...seed].reduce((sum, ch) => sum + ch.charCodeAt(0), 0);
  const index = (hash % BUILDING_ILLUSTRATION_COUNT) + 1;
  return `/images/building-0${index}.svg`;
}

export const NEARBY_SUBWAY = [
  { line: "8호선", station: "문정역", distance: "220m" },
  { line: "8호선", station: "장지역", distance: "660m" },
  { line: "3호선", station: "가락시장역", distance: "1,020m" },
];

export const NEARBY_BUS = [
  { name: "마을 송파02", distance: "110m" },
  { name: "간선 345", distance: "160m" },
  { name: "간선 302", distance: "160m" },
  { name: "지선 3322", distance: "160m" },
];

export const listings: Listing[] = [
  {
    id: 10222,
    title: "문정역 인근 100평 대형 사무실 · 풀인테리어",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "사무실",
    labels: ["추천"],
    themes: ["대형 사무실", "풀인테리어", "초역세권"],
    deposit: 15000,
    rent: 1200,
    maintenanceFee: 1000000,
    areaExclusive: 256.26,
    areaSupply: 501.36,
    floorCurrent: 5,
    floorTotal: 15,
    direction: "북향 (주된 출입구 기준)",
    mainUse: "업무시설(사무소)",
    parkingCount: 619,
    elevatorCount: 10,
    moveInDate: "즉시입주 협의가능",
    description:
      "실 100평, 특A급 풀인테리어 사무실입니다. 문정역 도보 5분, 지금 바로 입주 가능합니다.",
    thumbnail: PLACEHOLDER_IMG("10222"),
    images: [PLACEHOLDER_IMG("10222"), PLACEHOLDER_IMG("10222-2")],
    lat: 37.4859,
    lng: 127.1226,
  },
  {
    id: 10221,
    title: "문정동 52평 사무실 · 즉시 입주 가능",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "사무실",
    labels: ["추천", "전속"],
    themes: ["중형 사무실", "풀인테리어"],
    deposit: 6000,
    rent: 530,
    maintenanceFee: 550000,
    areaExclusive: 152.11,
    areaSupply: 280.2,
    floorCurrent: 7,
    floorTotal: 12,
    direction: "남향",
    mainUse: "업무시설(사무소)",
    parkingCount: 80,
    elevatorCount: 4,
    moveInDate: "즉시입주 가능",
    description: "실 52평, 룸 2개, 탕비실 완비된 깔끔한 사무실입니다.",
    thumbnail: PLACEHOLDER_IMG("10221"),
    images: [PLACEHOLDER_IMG("10221")],
    lat: 37.4849,
    lng: 127.1207,
  },
  {
    id: 10220,
    title: "문정역 역세권 90평 사무실 · 업무시설 최적화",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "사무실",
    labels: ["추천"],
    themes: ["대형 사무실", "풀인테리어", "즉시입주 가능"],
    deposit: 10000,
    rent: 900,
    maintenanceFee: 900000,
    areaExclusive: 230.85,
    areaSupply: 420.1,
    floorCurrent: 3,
    floorTotal: 10,
    direction: "동향",
    mainUse: "업무시설(사무소)",
    parkingCount: 50,
    elevatorCount: 3,
    moveInDate: "즉시입주 가능",
    description: "실 90평, 몸만 들어와서 바로 업무 가능한 풀인테리어 사무실.",
    thumbnail: PLACEHOLDER_IMG("10220"),
    images: [PLACEHOLDER_IMG("10220")],
    lat: 37.4867,
    lng: 127.1233,
  },
  {
    id: 10014,
    title: "문정동 190평 사무실 · 1개층 단독사용",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "사무실",
    labels: ["추천", "대형평수"],
    themes: ["대형 사무실", "주차가능", "즉시입주 가능", "초역세권", "풀인테리어"],
    deposit: 30000,
    rent: 3000,
    maintenanceFee: null,
    areaExclusive: 625.19,
    areaSupply: 875.8,
    floorCurrent: 4,
    floorTotal: 11,
    direction: "동향 (주된 출입구 기준, 한개층단독사용)",
    mainUse: "업무시설(사무소)",
    parkingCount: 111,
    elevatorCount: 2,
    moveInDate: "즉시입주 협의가능",
    description:
      "실 190평, 1개층 단독사용 사무실입니다. 렌트프리 핏아웃 협의 가능하며, 월세에 관리비가 포함되어 있습니다.",
    thumbnail: PLACEHOLDER_IMG("10014"),
    images: [PLACEHOLDER_IMG("10014"), PLACEHOLDER_IMG("10014-2")],
    lat: 37.4855,
    lng: 127.1215,
  },
  {
    id: 10006,
    title: "테라타워1 고층 사무실 · 문정역 도보권",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "매매",
    propertyType: "사무실",
    labels: ["추천"],
    themes: ["대형 사무실", "초역세권"],
    deposit: 0,
    salePrice: 367000,
    maintenanceFee: 950000,
    areaExclusive: 272.8,
    areaSupply: 480.5,
    floorCurrent: 8,
    floorTotal: 15,
    direction: "남서향",
    mainUse: "업무시설(사무소)",
    parkingCount: 200,
    elevatorCount: 6,
    moveInDate: "즉시입주 가능",
    description: "문정역 랜드마크 테라타워1, 특A급 전망의 실입주 매매 매물.",
    thumbnail: PLACEHOLDER_IMG("10006"),
    images: [PLACEHOLDER_IMG("10006")],
    lat: 37.4872,
    lng: 127.1219,
  },
  {
    id: 10023,
    title: "문정동 12평 소형 사무실 · 룸 1개",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "사무실",
    labels: ["추천"],
    themes: ["소형 사무실", "풀인테리어"],
    deposit: 1500,
    rent: 120,
    maintenanceFee: 150000,
    areaExclusive: 39.6,
    areaSupply: 70.2,
    floorCurrent: 2,
    floorTotal: 8,
    direction: "남향",
    mainUse: "업무시설(사무소)",
    parkingCount: 20,
    elevatorCount: 2,
    moveInDate: "즉시입주 가능",
    description: "룸 1개, 아담하고 깔끔한 소형 사무실입니다.",
    thumbnail: PLACEHOLDER_IMG("10023"),
    images: [PLACEHOLDER_IMG("10023")],
    lat: 37.4841,
    lng: 127.1198,
  },
  {
    id: 10212,
    title: "문정역 초역세권 200평 상가 · 체육시설 적합",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "상가",
    labels: ["추천"],
    themes: ["초역세권"],
    deposit: 30000,
    rent: 1900,
    maintenanceFee: null,
    areaExclusive: 662.54,
    areaSupply: 1100.2,
    floorCurrent: -1,
    floorTotal: 5,
    direction: "-",
    mainUse: "근린생활시설",
    parkingCount: 40,
    elevatorCount: 2,
    moveInDate: "협의가능",
    description: "체육시설 업종에 적합한 문정역 초역세권 대형 상가입니다.",
    thumbnail: PLACEHOLDER_IMG("10212"),
    images: [PLACEHOLDER_IMG("10212")],
    lat: 37.4863,
    lng: 127.1244,
  },
  {
    id: 10020,
    title: "엠스테이트 오피스텔 · 깔끔한 인테리어",
    address: "서울 송파구 문정동",
    district: "서울 송파구 문정동",
    dealType: "월세",
    propertyType: "오피스텔",
    labels: ["추천"],
    themes: ["중형 사무실", "초역세권"],
    deposit: 3000,
    rent: 320,
    maintenanceFee: 300000,
    areaExclusive: 94.52,
    areaSupply: 160.4,
    floorCurrent: 9,
    floorTotal: 20,
    direction: "남동향",
    mainUse: "업무시설(오피스텔)",
    parkingCount: 150,
    elevatorCount: 4,
    moveInDate: "즉시입주 가능",
    description: "문정역 랜드마크 엠스테이트, 깔끔한 인테리어 오피스텔.",
    thumbnail: PLACEHOLDER_IMG("10020"),
    images: [PLACEHOLDER_IMG("10020")],
    lat: 37.4877,
    lng: 127.1209,
  },
];

export function getListingById(id: number): Listing | undefined {
  return listings.find((item) => item.id === id);
}

export function getRelatedListings(current: Listing, limit = 6): Listing[] {
  return listings
    .filter((item) => item.id !== current.id && item.district === current.district)
    .slice(0, limit);
}
