import {
  LayoutDashboard,
  Building2,
  Plus,
  MapPin,
  EyeOff,
  Trash2,
  Tags,
  Image,
  Landmark,
  Grid3x3,
  ListChecks,
  NotebookPen,
  Compass,
  Users,
  Home,
  CalendarDays,
  Search,
  FileText,
  Mail,
  ShieldCheck,
  Lock,
  TrendingUp,
  Wallet,
  FileSignature,
  Newspaper,
  MoreHorizontal,
  Palette,
  Settings,
  Sparkles,
  Handshake,
  Bot,
  type LucideIcon,
} from "lucide-react";

export type MenuLeaf = { key: string; label: string; icon: LucideIcon };
export type MenuItem = MenuLeaf & { children?: MenuLeaf[] };

export const MENU: MenuItem[] = [
  { key: "dashboard", label: "대시보드", icon: LayoutDashboard },
  {
    key: "property",
    label: "매물 관리",
    icon: Building2,
    children: [
      { key: "property-list", label: "전체 매물 목록", icon: Building2 },
      { key: "property-register", label: "매물 등록", icon: Plus },
      { key: "property-map", label: "지도", icon: MapPin },
      { key: "property-private", label: "비공개 매물", icon: EyeOff },
      { key: "property-deleted", label: "삭제된 매물", icon: Trash2 },
      { key: "property-category", label: "매물 종류 관리", icon: Tags },
      { key: "property-gallery", label: "매물 사진첩", icon: Image },
      { key: "property-complex", label: "단지 정보 관리", icon: Landmark },
      { key: "property-complex-icon", label: "단지 아이콘 관리", icon: Grid3x3 },
      { key: "property-complex-system", label: "단지 시스템 목록", icon: ListChecks },
      { key: "property-log", label: "매물 일지", icon: NotebookPen },
    ],
  },
  { key: "field-visit", label: "임장 관리", icon: Compass },
  { key: "customer-inquiry", label: "고객·문의 관리", icon: Users },
  { key: "home-request", label: "매물 요청 관리", icon: Home },
  { key: "schedule", label: "일정 관리", icon: CalendarDays },
  { key: "data-search", label: "데이터 검색", icon: Search },
  { key: "realestate-info", label: "부동산 정보", icon: FileText },
  { key: "memo", label: "쪽지 / 문의", icon: Mail },
  {
    key: "staff",
    label: "관리자 / 직원 관리",
    icon: ShieldCheck,
    children: [
      { key: "staff-role", label: "직원 권한", icon: ShieldCheck },
      { key: "group-permission", label: "그룹별 권한 설정", icon: Lock },
    ],
  },
  { key: "deal-case", label: "매매사례 관리", icon: TrendingUp },
  { key: "payment-payroll", label: "입금 및 급여관리", icon: Wallet },
  { key: "provisional-contract", label: "가계약 / 입실퇴거 관리", icon: FileSignature },
  { key: "board", label: "게시판 관리", icon: Newspaper },
  { key: "etc", label: "기타 기능", icon: MoreHorizontal },
  {
    key: "site-settings",
    label: "홈페이지 설정",
    icon: Palette,
    children: [
      { key: "site-screen", label: "화면 설정", icon: Palette },
      { key: "site-advanced", label: "고급 설정", icon: Settings },
      { key: "ai-settings", label: "AI 고급 설정", icon: Sparkles },
    ],
  },
  { key: "partners", label: "제휴 업체", icon: Handshake },
  { key: "ai-search", label: "AI 매물 탐색", icon: Sparkles },
  { key: "chatbot", label: "매물 챗봇", icon: Bot },
];

export const FLAT_MENU: MenuLeaf[] = MENU.flatMap((item) => item.children ?? [item]);
